export const sample_foods = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        price: 100,
        cookTime: '10-20',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'food-8.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 200,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'chine'],
        stars: 5,
        imageUrl: "food-2.jpg",
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 50,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 4.0,
        imageUrl: 'food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 60,
        cookTime: '10-15',
        favorite: false,
        origins: ['belgium', 'france'],
        stars: 3.5,
        imageUrl: 'food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 220,
        cookTime: '20-30',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 150,
        cookTime: '25-30',
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'food-9.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
]


export const sample_tags = [
    {name: "All", count: 6 },
    {name: "FastFood", count: 4 },
    {name: "Pizza", count: 2 },
    {name: "Lunch", count: 3 },
    {name: "SlowFood", count: 2 },
    {name: "Hamburger", count: 1 },
    {name: "Fry", count: 1 },
    {name: "Soup", count: 1 },  
];